# Generated by Django 6.0.6 on 2026-06-16 08:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("datasets", "0002_alter_dataset_original_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("row_count", models.IntegerField(default=0)),
                ("column_count", models.IntegerField(default=0)),
                ("missing_values", models.JSONField(default=dict)),
                ("duplicate_rows", models.IntegerField(default=0)),
                ("unique_value_summary", models.JSONField(default=dict)),
                ("data_type_summary", models.JSONField(default=dict)),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "dataset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="datasets.dataset",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
