# Generated by Django 6.0.6 on 2026-06-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetprofile",
            name="column_names",
            field=models.JSONField(default=list),
        ),
    ]
