# Generated by Django 6.0.6 on 2026-06-18 06:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("datasets", "0002_alter_dataset_original_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="CleaningJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("rows_before", models.IntegerField(default=0)),
                ("rows_after", models.IntegerField(default=0)),
                ("duplicates_removed", models.IntegerField(default=0)),
                (
                    "cleaned_file",
                    models.FileField(blank=True, null=True, upload_to="cleaned/"),
                ),
                ("cleaning_summary", models.JSONField(default=dict)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cleaning_jobs",
                        to="datasets.dataset",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
